  datasource:
    url: jdbc:oracle:thin:@chenky3-w10:1521:xe
    username: kyrie
    password: 123456789
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    database: oracle